<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);SKEXP0001;SKEXP0010;SKEXP0070</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\DocuMind.Domain\DocuMind.Domain.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.SemanticKernel" Version="1.32.0" />
    <PackageReference Include="Microsoft.SemanticKernel.Connectors.Ollama" Version="1.32.0-alpha" />
    <PackageReference Include="PdfPig" Version="0.1.9" />
  </ItemGroup>
</Project>
